[project]
name = "hw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "dotenv>=0.9.9",
    "jaxn>=0.0.1",
    "pydantic-ai>=1.20.0",
    "requests>=2.32.5",
]
